import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    const [user, setUser] = useState(null);
    const router = useRouter();

    useEffect(() => {
        if (localStorage.getItem("userInfo")) {
            const userInfo = JSON.parse(
                localStorage.getItem("userInfo") || "{}"
            );
            setUser(userInfo);
        }
        console.log(user);
    }, []);

    return (
        <div>
            <Head>
                <title>Elearning</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header user={user} />
        </div>
    );
};

export default Home;
